### ISSUE TITLE
Running small dataset on CPU

### ISSUE THREAD

**Issue by asaksena98** [facebookresearch/fastMRI#40] opened 2020-06-01 18:45 UTC
hello, I am running into some issues when I attempt to run the train_unet script on a small dataset on my local environment (which does not have any GPU capabilities). 

When I run the script with the --gpus argument set to 0, I get the following error message:
` File "/Users/abhinavsaksena/mri/fastMRI/env/lib/python3.7/site-packages/torch/utils/tensorboard/summary.py", line 156, in hparams
    raise ValueError('value should be one of int, float, str, bool, or torch.Tensor')
ValueError: value should be one of int, float, str, bool, or torch.Tensor `

If I try to change the --gpu arg to 1, I get the following message:
`  File "/Users/abhinavsaksena/mri/fastMRI/env/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 533, in sanitize_gpu_ids
    raise MisconfigurationException(message)
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
`

How might I go about fixing these issues and run the code on my CPU? Here are some similar issues I found online for reference:
[https://github.com/PyTorchLightning/pytorch-lightning/pull/609](url)
[https://github.com/PyTorchLightning/pytorch-lightning/issues/899](url)

**Comment by anuroopsriram** [comment] 2020-06-01 23:22
Hi: You would have to remove this line to run on the CPU:
https://github.com/facebookresearch/fastMRI/blob/master/models/unet/train_unet.py#L186

You can also change the line to the following and then use `--gpus 0`:
`gpus=(args.gpus if args.gpus > 0 else None)`

**Comment by asaksena98** [comment] 2020-06-02 19:08
Hello, thank you for your response. I had previously tried the first suggestion but it didn't work. The second one doesn't seem to work as well. I believe it might be some kind of issue with the version of pytorch-lightning being used (0.6.0).

**Comment by mmuckley** [comment] 2020-06-03 20:44
This is confusing. `argparse` should cast it to an `int` so there should be no problem. I just ran it on my system with the first option, no error related to `tensorboard`. Let us know if you are able to fix this.

**Comment by asaksena98** [comment] 2020-06-03 21:09
I updated the pytorch-lightning version to 0.7.6 and that seemed to fix it.

**Comment by mmuckley** [comment] 2020-06-03 21:10
Closing this as the problem is fixed.

**Closed by mmuckley** 2020-06-03 21:10 UTC
