### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by jiangwenjie123** [facebookresearch/fastMRI#107] opened 2020-11-15 15:44 UTC
Hello, take the liberty to bother me, do you have fastmri_examples/varnet and fastmri_examples/unet trained models? Is it easy to share if there are? My email is 729081987@qq.com, or you can put it in Google Cloud Disk, I will download it when that happens, thank you so much!

**Comment by mmuckley** [comment] 2020-11-15 15:47
Closing this, duplicate of #106. We'll be publishing the models to everyone.

**Closed by mmuckley** 2020-11-15 15:47 UTC
